[
    EnabledBySetting=TrustedTypesEnabled,
    Exposed=(Window,Worker)
]
interface TrustedScript {
  stringifier;
  DOMString toJSON();
  static TrustedScript fromLiteral(object templateStringsArray);
};

