[
    EnabledBySetting=TrustedTypesEnabled,
    Exposed=(Window,Worker)
]
interface TrustedScriptURL {
  stringifier;
  DOMString toJSON();
  static TrustedScriptURL fromLiteral(object templateStringsArray);
};

