[
    EnabledBySetting=TrustedTypesEnabled,
    ImplementedBy=WindowOrWorkerGlobalScopeTrustedTypes
] partial interface mixin WindowOrWorkerGlobalScope {
    [CallWith=CurrentScriptExecutionContext, SameObject] readonly attribute TrustedTypePolicyFactory trustedTypes;
};
